/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DailyBookRouteImport } from './routes/daily-book'
import { Route as DriverVouchersRouteImport } from './routes/driver-vouchers'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BillsIndexRouteImport } from './routes/bills.index'
import { Route as BillsCreateRouteImport } from './routes/bills.create'
import { Route as ReportsAgingRouteImport } from './routes/reports.aging'
import { Route as ReportsOutstandingRouteImport } from './routes/reports.outstanding'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyBookRoute = DailyBookRouteImport.update({
  id: '/daily-book',
  path: '/daily-book',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverVouchersRoute = DriverVouchersRouteImport.update({
  id: '/driver-vouchers',
  path: '/driver-vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIndexRoute = BillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsCreateRoute = BillsCreateRouteImport.update({
  id: '/bills/create',
  path: '/bills/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAgingRoute = ReportsAgingRouteImport.update({
  id: '/reports/aging',
  path: '/reports/aging',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsOutstandingRoute = ReportsOutstandingRouteImport.update({
  id: '/reports/outstanding',
  path: '/reports/outstanding',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily-book': typeof DailyBookRoute
  '/driver-vouchers': typeof DriverVouchersRoute
  '/ledger': typeof LedgerRoute
  '/masters': typeof MastersRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/bills/create': typeof BillsCreateRoute
  '/reports/aging': typeof ReportsAgingRoute
  '/reports/outstanding': typeof ReportsOutstandingRoute
  '/bills/': typeof BillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily-book': typeof DailyBookRoute
  '/driver-vouchers': typeof DriverVouchersRoute
  '/ledger': typeof LedgerRoute
  '/masters': typeof MastersRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/bills/create': typeof BillsCreateRoute
  '/reports/aging': typeof ReportsAgingRoute
  '/reports/outstanding': typeof ReportsOutstandingRoute
  '/bills': typeof BillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily-book': typeof DailyBookRoute
  '/driver-vouchers': typeof DriverVouchersRoute
  '/ledger': typeof LedgerRoute
  '/masters': typeof MastersRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/bills/create': typeof BillsCreateRoute
  '/reports/aging': typeof ReportsAgingRoute
  '/reports/outstanding': typeof ReportsOutstandingRoute
  '/bills/': typeof BillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily-book'
    | '/driver-vouchers'
    | '/ledger'
    | '/masters'
    | '/payments'
    | '/settings'
    | '/bills/create'
    | '/reports/aging'
    | '/reports/outstanding'
    | '/bills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily-book'
    | '/driver-vouchers'
    | '/ledger'
    | '/masters'
    | '/payments'
    | '/settings'
    | '/bills/create'
    | '/reports/aging'
    | '/reports/outstanding'
    | '/bills'
  id:
    | '__root__'
    | '/'
    | '/daily-book'
    | '/driver-vouchers'
    | '/ledger'
    | '/masters'
    | '/payments'
    | '/settings'
    | '/bills/create'
    | '/reports/aging'
    | '/reports/outstanding'
    | '/bills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyBookRoute: typeof DailyBookRoute
  DriverVouchersRoute: typeof DriverVouchersRoute
  LedgerRoute: typeof LedgerRoute
  MastersRoute: typeof MastersRoute
  PaymentsRoute: typeof PaymentsRoute
  SettingsRoute: typeof SettingsRoute
  BillsCreateRoute: typeof BillsCreateRoute
  ReportsAgingRoute: typeof ReportsAgingRoute
  ReportsOutstandingRoute: typeof ReportsOutstandingRoute
  BillsIndexRoute: typeof BillsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-book': {
      id: '/daily-book'
      path: '/daily-book'
      fullPath: '/daily-book'
      preLoaderRoute: typeof DailyBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-vouchers': {
      id: '/driver-vouchers'
      path: '/driver-vouchers'
      fullPath: '/driver-vouchers'
      preLoaderRoute: typeof DriverVouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/': {
      id: '/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof BillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/create': {
      id: '/bills/create'
      path: '/bills/create'
      fullPath: '/bills/create'
      preLoaderRoute: typeof BillsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/aging': {
      id: '/reports/aging'
      path: '/reports/aging'
      fullPath: '/reports/aging'
      preLoaderRoute: typeof ReportsAgingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/outstanding': {
      id: '/reports/outstanding'
      path: '/reports/outstanding'
      fullPath: '/reports/outstanding'
      preLoaderRoute: typeof ReportsOutstandingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyBookRoute: DailyBookRoute,
  DriverVouchersRoute: DriverVouchersRoute,
  LedgerRoute: LedgerRoute,
  MastersRoute: MastersRoute,
  PaymentsRoute: PaymentsRoute,
  SettingsRoute: SettingsRoute,
  BillsCreateRoute: BillsCreateRoute,
  ReportsAgingRoute: ReportsAgingRoute,
  ReportsOutstandingRoute: ReportsOutstandingRoute,
  BillsIndexRoute: BillsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
